from typing import Optional

try:
    from pydantic_settings import BaseSettings
except ImportError:
    try:
        from pydantic import BaseSettings
    except ImportError:
        from pydantic import BaseModel
        class BaseSettings(BaseModel):
            pass

class Settings(BaseSettings):
    PROJECT_NAME: str = "Athenus Knowledge OS"
    VERSION: str = "0.1.0"
    API_V1_PREFIX: str = "/api/v1"
    
    # Environment
    ENVIRONMENT: str = "development"
    DEBUG: bool = True
    
    # Database & Local Storage
    DATABASE_URL: str = "sqlite:///./data/athenus.db"
    QDRANT_PATH: str = "./data/qdrant"
    QDRANT_COLLECTION: str = "transcript_chunks"
    UPLOADS_DIR: str = "./data/uploads"
    
    # Local Model Defaults
    DEFAULT_LLM_PROVIDER: str = "ollama"
    OLLAMA_BASE_URL: str = "http://localhost:11434"
    DEFAULT_LLM_MODEL: str = "llama3:8b"
    
    DEFAULT_STT_PROVIDER: str = "faster_whisper"
    WHISPER_MODEL_SIZE: str = "base"
    
    DEFAULT_EMBEDDING_PROVIDER: str = "sentence_transformers"
    EMBEDDING_MODEL_NAME: str = "BAAI/bge-small-en-v1.5"
    
    # IPC Auth Token (generated by Tauri on boot)
    IPC_BEARER_TOKEN: Optional[str] = None
    
    # Optional Cloud API Keys
    GROQ_API_KEY: Optional[str] = None
    OPENROUTER_API_KEY: Optional[str] = None
    GEMINI_API_KEY: Optional[str] = None
    CLAUDE_API_KEY: Optional[str] = None
    DEEPGRAM_API_KEY: Optional[str] = None

    class Config:
        env_file = (".env", "../.env")
        case_sensitive = True

settings = Settings()
