from typing import Optional

try:
    from pydantic_settings import BaseSettings, SettingsConfigDict
except ImportError:
    try:
        from pydantic import BaseSettings
        SettingsConfigDict = None
    except ImportError:
        from pydantic import BaseModel
        class BaseSettings(BaseModel):
            pass
        SettingsConfigDict = None

class Settings(BaseSettings):
    PROJECT_NAME: str = "Athenus Knowledge OS"
    VERSION: str = "0.1.0"
    API_V1_PREFIX: str = "/api/v1"
    
    # Environment
    ENVIRONMENT: str = "development"
    DEBUG: bool = True
    
    # Database & Local Storage
    DATABASE_URL: str = "sqlite:///./data/athenus.db"
    QDRANT_PATH: str = "./data/qdrant"
    QDRANT_COLLECTION: str = "transcript_chunks"
    UPLOADS_DIR: str = "./data/uploads"
    
    # LLM Settings & Base URLs
    LLM_PROVIDER: str = "ollama"
    LLM_MODEL: Optional[str] = None

    DEFAULT_LLM_PROVIDER: str = "ollama"
    OLLAMA_BASE_URL: str = "http://localhost:11434"
    OLLAMA_TIMEOUT: float = 3.0
    DEFAULT_LLM_MODEL: str = "llama3:8b"

    # OpenRouter
    OPENROUTER_BASE_URL: str = "https://openrouter.ai/api/v1"
    OPENROUTER_DEFAULT_MODEL: str = "google/gemini-2.5-flash"
    OPENROUTER_API_KEY: Optional[str] = None

    # Groq
    GROQ_BASE_URL: str = "https://api.groq.com/openai/v1"
    GROQ_DEFAULT_MODEL: str = "llama-3.3-70b-versatile"
    GROQ_API_KEY: Optional[str] = None

    # OpenAI
    OPENAI_BASE_URL: str = "https://api.openai.com/v1"
    OPENAI_DEFAULT_MODEL: str = "gpt-4o-mini"
    OPENAI_API_KEY: Optional[str] = None

    # Anthropic
    ANTHROPIC_BASE_URL: str = "https://api.anthropic.com/v1"
    ANTHROPIC_DEFAULT_MODEL: str = "claude-3-5-sonnet-latest"
    ANTHROPIC_API_KEY: Optional[str] = None

    # Custom OpenAI-Compatible Endpoints (JSON string)
    CUSTOM_LLM_PROVIDERS: Optional[str] = None

    # Multimodal & Other Cloud Keys
    GEMINI_API_KEY: Optional[str] = None
    CLAUDE_API_KEY: Optional[str] = None
    DEEPGRAM_API_KEY: Optional[str] = None

    # STT & Embeddings
    DEFAULT_STT_PROVIDER: str = "faster_whisper"
    WHISPER_MODEL_SIZE: str = "base"
    WHISPER_DEVICE: str = "cpu"
    WHISPER_COMPUTE_TYPE: str = "int8"
    
    DEFAULT_EMBEDDING_PROVIDER: str = "sentence_transformers"
    EMBEDDING_MODEL_NAME: str = "BAAI/bge-small-en-v1.5"
    
    # IPC Auth Token (generated by Tauri on boot)
    IPC_BEARER_TOKEN: Optional[str] = None

    if SettingsConfigDict is not None:
        model_config = SettingsConfigDict(
            env_file=(".env", "../.env"),
            case_sensitive=True,
            extra="ignore"
        )
    else:
        class Config:
            env_file = (".env", "../.env")
            case_sensitive = True

settings = Settings()
